### ISSUE TITLE
Module no longer works for Workstations, as HP has split into to seperate entites.

### ISSUE THREAD

**Issue by dotps1** [dotps1/HPWarranty#10]
HP has divided there company into servers and workstations, and one ISEE no longer works for both.  Currently, the module is working for Servers, but not workstations.

**Comment by jabateman** [comment]
Do you have information on an ISEE that will work with just workstations?

**Comment by dotps1** [comment]
I do not, as soon as i do, i will fix this module to work.  thanks.

**Comment by kelmansoury** [comment]
If you install Fiddler2 and enable the option to decrypt HTTPS Traffic, then download and install the HP Support Assistant on a HP workstation, then run a Warranty Check you get the following:

```http
POST https://es-ext-dh.austin.hp.com/es/ES10_1/ESListener HTTP/1.1
Content-Type: text/html
Host: es-ext-dh.austin.hp.com
Expect: 100-continue
Connection: Close
```

```xml
<?xml version="1.0" encoding="UTF-8"?>
<EIAMessage>
   <MessageHeader>
      <MessageID></MessageID>
      <TimeStamp></TimeStamp>
      <MessageType>request</MessageType>
      <ServiceDescriptor>
         <ServiceID>ES</ServiceID>
         <MajorVersion>8</MajorVersion>
         <MinorVersion>0</MinorVersion>
      </ServiceDescriptor>
      <MessageSecurity>
         <SecurityCredentials>
            <UserName>HPSF</UserName>
            <UserPassword>answer42</UserPassword>
         </SecurityCredentials>
      </MessageSecurity>
   </MessageHeader>
   <MessageBody>
      <EsRequestComplexType>
         <Operation>getEntitlementBySn</Operation>
         <ClientAppID>HPSF</ClientAppID>
         <EntitlementBySnRequest>
            <IsoCountryCd>{CountryCode}</IsoCountryCd>
            <EntitlementCheckDate>{EntitlementCheckDate}</EntitlementCheckDate>
            <SerialNumber>{SerialNumber}</SerialNumber>
            <ProductID>{ProductID}</ProductID>
            <ActiveContractsOnly>false</ActiveContractsOnly>
            <ActiveServicesOnly>false</ActiveServicesOnly>
            <ActiveWarrantyOnly>false</ActiveWarrantyOnly>
            <IncludeWarranty>true</IncludeWarranty>
            <IncludeContracts>true</IncludeContracts>
            <IncludeContacts>false</IncludeContacts>
            <IncludeAddresses>false</IncludeAddresses>
            <IncludeOffers>false</IncludeOffers>
            <IncludeDeliverables>false</IncludeDeliverables>
            <IncludeModifiers>false</IncludeModifiers>
            <IncludeServiceNotes>False</IncludeServiceNotes>
            <IncludeWorkings>false</IncludeWorkings>
            <WarrantySourceSystem />
         </EntitlementBySnRequest>
      </EsRequestComplexType>
   </MessageBody>
   <MessageTrailer />
</EIAMessage>
```

Values within curly brackets need to be substituted with their respective values.
The EntitlementCheckDate field must be -1000 day(s)/+1 day(s) to the current date.
Example: 2015-09-06.

It seems that MessageID and TimeStamp may be left empty.
The format for MessageID is as follows: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx and for the Timestamp: 2015-09-07T16:55:53.239Z

Could this be a viable solution bearing in mind that the API used does not seem to be public (as far as I know)?

**Comment by dotps1** [comment]
thanks for the info, i will try to look into it next week, ive been wrapped up on other projects.  thanks.

**Comment by beanska** [comment]
Based on Kelmansoury's info I took a look into the HP Support Assistant tool and was able to utilize the EntitlementService.dll to query my Laptop successfully.

    Add-Type -Path "C:\Program Files (x86)\Hewlett-Packard\HP Support Framework\Warranty\EntitlementService.dll"

    $p = New-Object 'system.collections.generic.dictionary[[string],[string]]'

    $p.Add("serialNo", "123456789ABC")
    $p.Add("countryCd", "US")
    $p.Add("url", "https://entitlement-ext.corp.hp.com/es/ES10_1/ESListener")
    $p.Add("productNo", "ABCDEFG#ABA")
    $p.Add("account", "")
    $p.Add("username", "HPSF")
    $p.Add("password", "answer42")
    $p.Add("includeServiceNotes", "true")

    $reqWriter = new-object HPWSD.RequestWriter($p)
    [xml] $reply = $reqWriter.sendMessage()

    $reply.EIAMessage.MessageBody.EsReply.CombinedUnitEntitlement

Thoughts?

**Comment by dotps1** [comment]
do you think we can redistribute the .dll, else, this will not work.  I'm not sure if we can use this because of that.

**Comment by beanska** [comment]
I am sure it *cannot* be redistributed but you could make the HP Support
software a prerequisite for the module to avoid that. Not ideal but on the
bright side it does make the query code more compact. On the other hand I
am sure one of us can figure out the full implementation given what has
been learned.

**Comment by beanska** [comment]
@kelmansoury Thanks for introducing me to Fiddler2 and for the above info. See pull request #12.

**Comment by kelmansoury** [comment]
@beanska @dotps1 Apologies for not getting back to you. I've not been actively following this thread.
The DLL file is indeed not required as you discovered later. Following my post above I managed to implement it into a program I was writing in C#, filling the appropriate information into the XML string and sending that to the appropriate URL with the appropriate headers using a WebRequest (see http://stackoverflow.com/questions/1277212/how-to-call-a-web-service-with-no-wsdl-in-net for an example), then processing the result as required.

A point to make is while this may not be required for this project, it is interesting to set the values of all the Include* attributes to true and see what output you get. You'll definitely want IncludeOffers as this will show you the warranty/contract type. Potentially IncludeAddresses could be useful if you want to find out the delivery address, etc.

**Comment by dotps1** [comment]
All,
Thanks to tremendous work by @beanska I believe I have gotten this module working again, and better then ever at that.  I was able to hardcode data into the old previous ```Invoke-HPWarrantyRegistrationRequest``` cmdlet, so I was able to eliminate that completely.  and for workstations, that's not even needed.  I do not have any Server info to test, but I have simplified this module to two functions:
```PowerShell
Get-HPWorkstationWarrantyEntitlement
Get-HPServerWarrantyEntitlement
```
I either need someone to donate time testing the Server function, or give me a Serialnumber and productnumber of a server.

I tried to mirror each function after themselves.  thus far, I'm pretty happy,  I'm sure there will be some bugs after all this was a total rewrite.  but, we are almost back up and running.

thanks everyone!

**Comment by jplandry908** [comment]
I tested about 10 servers and 10 workstations and all appear to be working well. Great job! Thanks! :)

**Comment by dotps1** [comment]
That's great news, can do one last test for me, as far as the servers go?  I want to make sure the pipeline is working right, can you test with both of the following methods:

```PowerShell
@('Server1','Server2) | Get-HPServerWarrantyEntitlement

Get-HPServerWarrantyEntitlement -ComputerName 'Server1','Server2'
```

I would really appreciate it.  Thanks!

**Comment by jplandry908** [comment]
I'm not on the network of the servers at this time. I testing both functions passing the serial and product numbers using (-serialnumber & -productnumber). When I get back to the network with some HP server (probably within the week), I can run some more tests for you.

**Comment by dotps1** [comment]
greatly appreciated, thank you!

**Comment by dotps1** [comment]
As base functionality has been restored, I am closing this issue.  Thanks everyone for all your help.

**Comment by jplandry908** [comment]
My apologies, but I just realized that the HP servers I tested were actually getting results from the Workstation function. I forced it to use the Server function and found an error i the code. The function's replace statement has: ".Replace('<[!--ProductNumber--!]>', $ProductNumber)". However, the XML has: "<ProductNumber><[!--ProductID--!]></ProductNumber>" Once you make those the same, the function seems to work fine. I'm not getting any results though (or errors), but I am getting the server results on the workstation function.

**Comment by dotps1** [comment]
strange, yeah I just seen that on in the xml.  I fixed it, there was a second error in the too, using the Gdid for the serial number, can you grab the version I just checked in, and see if you get server results with the server cmdlet?

**Comment by jplandry908** [comment]
The XML looks good and the $request appears to be formatted correctly. I am still not getting results, but I think it is the servers since they are so old. I just looked at the response and "$entitlement."ISEE-GetOOSEntitlementInfoResponse".data.EIAError" is giving the following response:

type        : EIAError
xsi         : http://www.w3.org/2001/XMLSchema-instance
TimeStamp   : 2015-09-29T18:04:06.404
ErrorLevel  : FUNCTIONAL
ErrorID     : 214
ErrorText   : Product or part not eligible for warranty
ErrorClass  : DataNotFound
DataPayLoad : Source WARRANTY SWOP 2016: This product is not
                              eligible for HP Enterprise warranty; Support is obtained
                              from HP Inc                             . [TXID 6675684947]

I guess this is why I am getting the correct results using the Workstation function.

**Comment by dotps1** [comment]
makes sense, I actually just added a check in the Server cmdlet to look for that ErrorID and ErrorClass, if it finds it, it will throw an error.

although, I guess, I could have it just run the Get-Workstation, and then, this could all be one cmdlet!

hmmmmmmmm.

**Comment by jplandry908** [comment]
That's similar to why my code does. All machines are reporting to a central DB and then I a have a regularly scheduled job that runs and pulls the data from the DB and checks the warranties across different manufacturers. For HP, it is currently calling the workstation function and if no results are found, then calling the server function.

**Comment by dotps1** [comment]
yeah, I like it, I'm going to merge these into one function ```Get-HPWarrantyEntitlment``` if it throw that error will then default to the Workstation method.

Thanks for all the help!

**Comment by jplandry908** [comment]
No problem. I appreciate your hard work. Now I can remove the HP .DLL workaround I had in place that someone else suggested trying. :)

**Comment by dotps1** [comment]
checked in.  thanks.

**Comment by kentucker5** [comment]
Hello there
I recently setup Get-HPIncWarrantyEntitlement  and trying to check warranty for HPN (HP Networking). Can someone tell me if this should work? 

Getting:

PS U:\> Import-Csv u:\import.csv | Get-HPIncWarrantyEntitlement | Export-Csv u:\export.csv
Get-HPIncWarrantyEntitlement : Source WARRANTY SWOP 2016: This product is not eligible for HP Inc warranty; Support is obtained from Hewlett Packard Enterprise         . [TXID 6868711823]
At line:1 char:28
+ Import-Csv u:\import.csv | Get-HPIncWarrantyEntitlement | Export-Csv  ...
+                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : 214,Get-HPIncWarrantyEntitlement

Thanks
Ken

**Comment by dotps1** [comment]
basically, if you read the error it tells you exactly what you need to know: `Source WARRANTY SWOP 2016: This product is not eligible for HP Inc warranty; Support is obtained from Hewlett Packard Enterprise . [TXID 6868711823]`.  You are trying to use `Get-HPIncWarrantyEntitlment` which is for workstations, and `Get-HPWarrantyEntitlement` is for Enterprise Warranties, IE Servers.  so if you change the cmdlet, you should be fine.

```PowerShell
Import-Csv u:\import.csv | Get-HPWarrantyEntitlement | Export-Csv u:\export.csv
```

now, if you have workstations in that csv, you will get an error saying the opposite.  That is why this is such a PITA because there is two separate place and methods that need to be used with looking up workstations and server warranties.

Hope that helps.

**Comment by kentucker5** [comment]
Hi Thomas

I had tried that one also but it doesn’t look good.

See output below

PS U:\> Import-Csv u:\import.csv | Get-HPWarrantyEntitlement | Export-Csv u:\export.csv
Exception calling "GetResponse" with "0" argument(s): "The operation has timed out"
At C:\Program Files\WindowsPowerShell\Modules\HPWarranty\2.3.1.0\Functions\_Helper.Invoke-SOAPRequest.ps1:87 char:5
+     $responseStream = ($soapWebRequest.GetResponse()).GetResponseStre ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException
You cannot call a method on a null-valued expression.
At C:\Program Files\WindowsPowerShell\Modules\HPWarranty\2.3.1.0\Functions\_Helper.Invoke-SOAPRequest.ps1:90 char:5
+     $returnXml = [Xml]$soapReader.ReadToEnd()
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
You cannot call a method on a null-valued expression.
At C:\Program Files\WindowsPowerShell\Modules\HPWarranty\2.3.1.0\Functions\_Helper.Invoke-SOAPRequest.ps1:92 char:5
+     $responseStream.Close()
+     ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
Get-HPWarrantyEntitlement : No entitlement found.
At line:1 char:28
+ Import-Csv u:\import.csv | Get-HPWarrantyEntitlement | Export-Csv u:\ ...
+                            ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-HPWarrantyEntitlement


Thanks
Ken

**Comment by dotps1** [comment]
This looks like another issue un related.  can you open a separate bug for this?

I will start taking a look, thanks.

**Comment by kentucker5** [comment]
Thanks Thomas

I opened a new issue:
https://github.com/dotps1/HPWarranty/issues/22

Regards
Ken

**Comment by dotps1** [comment]
closing, see issue #24
